### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cschoeni** [OfficeDev/office-js-docs-pr#375]
Error according to the instructions on https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular:

PS: Since yo office unfortunately didn't prepare the angular project as expected so that work can start directly, I tried to install everything cleanly with --output. But this doesn't work.

testCreateWordAddIn (master) $ npm run start

> test-create-word-add-in@0.0.0 start /Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn
> ng serve --ssl true --port 3000

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(defaults).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(defaults).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/@angular-devkit/core/src/workspace/workspace.js:198:42)
    at MergeMapSubscriber._tryNext (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/Subscriber.js:68:18)
    at MergeMapSubscriber.notifyNext (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/operators/mergeMap.js:90:26)
    at InnerSubscriber._next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/Subscriber.js:68:18)
    at MapSubscriber._next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/Subscriber.js:68:18)
    at SwitchMapSubscriber.notifyNext (/Users/cschoeni/Teko/Diplomarbeit/testCreateWordAddIn/node_modules/rxjs/internal/operators/switchMap.js:83:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-create-word-add-in@0.0.0 start: `ng serve --ssl true --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-create-word-add-in@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cschoeni/.npm/_logs/2018-09-17T18_47_45_331Z-debug.log
testCreateWordAddIn (master) $

**Comment by kbrandl** [comment]
@cschoeni thanks for reporting this issue and sorry to hear that you're having trouble with the Excel - Angular quick start. Unfortunately it seems that recent changes to the way Yo Office creates the add-in project have rendered parts of the current instructions invalid. We'll be updating this quick start soon to address these issues.

**Comment by kbrandl** [comment]
@cschoeni Thanks again for raising this issue. We've significantly revised the Excel-Angular quick start, to reflect that the Yeoman generator for Office Add-ins is now the recommended way of generating an Office Add-in project using the Angular framework. Please give the new instructions a try and feel free to reach out again if you have any trouble.
