### ISSUE TITLE
Could not create project with Yeoman

### ISSUE THREAD

**Issue by chuyaowang** [OfficeDev/office-js-docs-pr#3937]
Hi, I tried to follow the tutorial but could not create a project with Yeoman. I am using a M1 macbook with macOS Monterey 12.6.3 
Error as follows:
```
AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/usr/local/lib/node_modules/generator-office/node_modules/follow-redirects/index.js:521:14)
    at dispatchHttpRequest (/usr/local/lib/node_modules/generator-office/node_modules/axios/dist/node/axios.cjs:2810:21)
    at new Promise (<anonymous>)
    at http (/usr/local/lib/node_modules/generator-office/node_modules/axios/dist/node/axios.cjs:2520:10)
    at Axios.dispatchRequest (/usr/local/lib/node_modules/generator-office/node_modules/axios/dist/node/axios.cjs:3481:10)
    at Axios.request (/usr/local/lib/node_modules/generator-office/node_modules/axios/dist/node/axios.cjs:3831:33)
    at wrap (/usr/local/lib/node_modules/generator-office/node_modules/axios/dist/node/axios.cjs:29:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-office/generators/app/helpers/helperMethods.js:51:40)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/generator-office/generators/app/helpers/helperMethods.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/generator-office/generators/app/helpers/helperMethods.js:4:12)
    at Object.downloadProjectTemplateZipFile (/usr/local/lib/node_modules/generator-office/generators/app/helpers/helperMethods.js:49:16)
    at module.exports.<anonymous> (/usr/local/lib/node_modules/generator-office/generators/app/index.js:317:61)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/generator-office/generators/app/index.js:8:71
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@chuyaowang Thanks for letting us know about this.

@millerds Can you take a look?

Thanks.
