### ISSUE TITLE
Custom Functions not working on macOS

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/office-js-docs-pr#523]
I've created a sample Add-in to try custom functions in Excel on macOS. 

The Add-in loads correctly but none of the custom functions can be executed from within Excel. Excel just prints `#NAME?`.

macOS: 10.13.6
Excel for Mac: 16.19 Build 181024

Office Insider program is joined by setting insider builds to `Office Insider Fast` in *Microsoft AutoUpdate*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hey @ThorstenHans, can you try this branch: https://github.com/OfficeDev/Excel-Custom-Functions/tree/Preview_May_2018?

Will need to follow up with team on  monday

**Comment by ThorstenHans** [comment]
Hey @keyur32, 

thanks for the hint. No need to rush. I've tried the branch, unfortunately with no luck. At runtime, I receive the same `#NAME?`. Also looked at the formula builder in Excel but it's not showing any of the custom `CONTOSO.*` formulas.

The branch is a kind of outdated. First users need to upgrade `webpack-cli` to version 3.

For other users facing issues like

```
/Users/me/dev/public/sample/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/me/dev/public/sample/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/Users/me/dev/public/sample/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```
an Upgrade of `webpack-cli` from version `2.x.x` to `3.x.x` is required, install it by executing 

```
npm i webpack-cli@3 --save-dev
```

**Comment by keyur32** [comment]
Thanks, looks like there's a registration issue. Sent you an invite to debug tomm; hunch is you are on a build that now requires the 'id' parameter to be specified in your customfunctions.json metadata for each function.

**Comment by kbrandl** [comment]
Transferring this issue to the Excel-Custom-Functions repo. @keyur32 -- any update on this issue?
