### ISSUE TITLE
Error on startup when creating React Excel Addinwith Yeoman

### ISSUE THREAD

**Issue by ericklind** [OfficeDev/office-js-docs-pr#579]
I'm trying to run the office setup for Excel using yo.  When I try to run the app, I get the following error:
```
$ npm start

> sift-addin@1.0.0 start C:\Users\ecloward.ODA\source\repos\sift.addin
> webpack-dev-server --inline --config config/webpack.dev.js --progress

C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:363
    throw err;
    ^

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\lib\Server.js:114:49)
    at new Server (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\lib\Server.js:127:5)
    at startDevServer (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:355:14)
    at processOptions (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:309:5)
    at Object.<anonymous> (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:424:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sift-addin@1.0.0 start: `webpack-dev-server --inline --config config/webpack.dev.js --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sift-addin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ecloward.ODA\AppData\Roaming\npm-cache\_logs\2018-11-27T00_32_57_505Z-debug.log

```
Please let me know how to resolve this or if there is a better way to get running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ccc61e-06b1-fd30-63a0-625301ea0bc8
* Version Independent ID: 1fdff452-de8f-5b97-9f53-389eb9576b25
* Content: [Build an Excel add-in using React](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react)
* Content Source: [docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-react.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@ericklind sorry to hear that you're having trouble using the Yeoman Generator for Office Add-ins (aka "Yo Office") to create an Excel add-in with React. Issues in this GitHub repo are intended to report problems with the Office Add-ins documentation, but this seems like a problem with Yeoman Generator for Office Add-ins itself. Therefore, I'm going to transfer this issue to the [OfficeDev/generator-office](https://github.com/OfficeDev/generator-office) repo instead.
